# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Food Oasis Los Angeles
email: contact@foodoasis.la
description: > # this means to ignore newlines until "baseurl:"
  A list of healthy food locations in Los Angeles
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://foodoasis.la" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: foodoasisla
github_username: foodoasisla
permalink: pretty

# Build settings
markdown: kramdown
# theme: minima
# gems:
#  - jekyll-feed
exclude:
  - CNAME
  - README

keep_files:
  - .git
  - .gitignore
  - .nojekyll
  - CNAME
  - README

defaults:
  - scope:
      path: ""
      type: community-garden
    values:
      layout: location-details
      classname: location-details community-garden
      color: lime
  - scope:
      path: ""
      type: community-garden-from-staging-api
    values:
      layout: location-details
      classname: location-details community-garden
      color: lime
  - scope:
      path: ""
      type: farmers-market
    values:
      layout: location-details
      classname: location-details farmers-market
      color: strawberry
  - scope:
      path: ""
      type: supermarket
    values:
      layout: location-details
      classname: location-details supermarket
      color: strawberry
  - scope:
      path: ""
      type: food-pantry
    values:
      layout: location-details
      classname: location-details food-pantry
      color: canteloupe
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: locations
    values:
      layout: location-details
      classname: location-details
      color: canteloupe

collections:
  community-garden:
    output: true
    permalink: /community-garden/:path/
  community-garden-from-staging-api:
    output: true
    permalink: /community-garden-from-staging-api/:path/
  farmers-market:
    output: true
    permalink: /farmers-market/:path/
  supermarket:
    output: true
    permalink: /supermarket/:path/
  food-pantry:
    output: true
    permalink: /food-pantry/:path/
  locations:
    output: true
    permalink: /locations/:path/
