---
title: Food Oasis Los Angeles
timezone: UTC
collections:
  community-garden:
    title: Community Garden
    output: true
    permalink: "/community-garden/:path/"
  community-garden-from-staging-api:
    title: Community Garden From Staging Api
    output: true
    permalink: "/community-garden-from-staging-api/:path/"
  farmers-market:
    title: Farmers Market
    output: true
    permalink: "/farmers-market/:path/"
  food-pantry:
    title: Food Pantry
    output: true
    permalink: "/food-pantry/:path/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: community-garden
  values:
    layout: location-details
    color: lime
- scope:
    path: ''
    type: community-garden-from-staging-api
  values:
    layout: location-details
    color: lime
- scope:
    path: ''
    type: farmers-market
  values:
    layout: location-details
    color: strawberry
- scope:
    path: ''
    type: food-pantry
  values:
    layout: location-details
    color: canteloupe
email: contact@foodoasis.la
description: 'A list of healthy food locations in Los Angeles

'
baseurl: ''
url: https://foodoasis.la
twitter_username: foodoasisla
github_username: foodoasisla
permalink: pretty
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
